### PR TITLE
Add system preference to theme switcher

### PR DESCRIPTION
**Pull request by C-Lodder**
Rewrite the switcher to add a default `system preference` state (positioned in the middle).

- If the switcher is **disabled**, the system preferred colour scheme will be used. This all done via Javascript using an event listener rather than CSS, primarily because I'd have to duplicate the dark theme variables. If you change your system colour scheme, the page will update automatyically.

- If the switcher is **enabled**, it's default state will be in the middle and use the system colour scheme.

- Theme will change to light/dark if switched accordingly and maintain its state on page refresh.

- If the switcher is set to dark or light, changing the system colour scheme will NOT affect the page.

@nikosdion If you could test on Safari, that would be much appreciated. I'll attach a zip file here incase you haven't got NodeJS installed to compile everything.

[tpl_lightning-v0.0.13-TEST.zip](https://github.com/C-Lodder/lightning/files/4996320/tpl_lightning-v0.0.13-TEST.zip)

### CODE REVIEW

**Comment by nikosdion** [comment]
I am using the package you provided to make sure that my NPM environment doesn't get in the way (I have set it up according to what is required for J4 core development).

> If the switcher is enabled, it's default state will be in the middle and use the system colour scheme.

Um, its default _internal_ state certainly appears to be the middle position but what is displayed is the left position. It does change colour scheme on page reload. It's not an important issue, just mildly confusing.

Other than that, everything you described works great. I am happy disabling the switcher and having the theme auto-switch on me. It works great!

**Comment by C-Lodder** [comment]
Ah it may be to the left if you had previously set the theme to "light" before this PR. If you try removing the localStorage manually, it should be in the middle.

**Comment by nikosdion** [comment]
Nope. My localStorage is empty – I just checked – but the switcher looks like this:
Screenshot 2020-07-30 at 11 12 24

It does _work_ right, despite appearances! I switch my Mac to Dark Mode, reload the page and the site is in dark mode. The localStorage is still empty and the switcher still looks to be in the left position:
image

**Comment by C-Lodder** [comment]
Turns out it wasn't working for me either. Issue hopefully all fixed now

[tpl_lightning-v0.0.12-BETA-2.zip](https://github.com/C-Lodder/lightning/files/5000201/tpl_lightning-v0.0.12-BETA-2.zip)

**Comment by nikosdion** [comment]
Yes, now it works correctly. Thank you!

**Comment by C-Lodder** [comment]
Thanks for testing

**Pull request merged**
